#!/bin/bash
set -e
git pull
source venv/bin/activate
pip install -r requirements.txt
python manage.py collectstatic --noinput
python manage.py makemigrations
python manage.py migrate
deactivate
npm ci --dev
./node_modules/.bin/parcel build bundles-src/index.js --dist-dir bundles --public-url="./"
systemctl restart starburger
systemctl reload nginx

echo "Deploy succesfull"
