# Generated by Django 5.2.4 on 2025-08-14 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_alter_orderitem_options_rename_name_order_firstname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='adress',
            new_name='address',
        ),
    ]
