# Generated by Django 5.2.4 on 2025-08-19 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_orderitem_price'),
    ]

    def copy_price_from_product_model_to_order_item_model(apps, schema_editor):
        OrderItem = apps.get_model('foodcartapp', 'Product')
        for product in OrderItem.objects.filter(price=1):
            product.price = product.product.price
            product.save()

    operations = [
        migrations.RunPython(copy_price_from_product_model_to_order_item_model),
    ]
