# Generated by Django 5.2.4 on 2025-08-20 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_auto_20250819_2144'),
    ]

    def copy_price_from_product_model_to_order_item_model(apps, schema_editor):
        OrderItem = apps.get_model('foodcartapp', 'OrderItem')
        products = OrderItem.objects.filter(price=1)
        for product in products.iterator():
            product.price = product.product.price
            product.save()

    operations = [
        migrations.RunPython(copy_price_from_product_model_to_order_item_model),
    ]