# Generated by Django 5.2.4 on 2025-08-21 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_alter_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('AC', 'Заказ принят'), ('BL', 'Сборка заказа'), ('SO', 'Доставка заказа'), ('FN', 'Заказ завершен')], default='Заказ принят', max_length=2),
        ),
    ]
