# Generated by Django 5.2.4 on 2025-08-21 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('AC', 'Заказ принят'), ('BL', 'Сборка заказа'), ('SO', 'Доставка заказа'), ('FN', 'Заказ завершен')], db_index=True, default='Заказ принят', max_length=2),
        ),
    ]
