# Generated by Django 5.2.4 on 2025-09-02 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0050_order_comment_alter_order_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(default=' ', max_length=450, verbose_name='Коментарий'),
        ),
    ]
