# Generated by Django 5.2.4 on 2025-09-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0053_alter_order_called_at_alter_order_delivered_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Наличными'), ('CARD', 'Электронно')], default='CARD', max_length=50, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('AC', 'Заказ принят'), ('BL', 'Сборка заказа'), ('SO', 'Доставка заказа'), ('FN', 'Заказ завершен'), ('NO', 'Необработанный')], db_index=True, default='Необработанный', max_length=2, verbose_name='Статус заказа'),
        ),
    ]
