# Generated by Django 5.2.4 on 2025-09-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0054_order_payment_method_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('AC', 'Заказ принят'), ('BL', 'Сборка заказа'), ('SO', 'Доставка заказа'), ('FN', 'Заказ завершен'), ('NO', 'Необработанный')], db_index=True, default='NO', max_length=2, verbose_name='Статус заказа'),
        ),
    ]
