# Generated by Django 5.2.4 on 2025-09-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0055_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Наличными'), ('CARD', 'Электронно')], db_index=True, default='CARD', max_length=50, verbose_name='Способ оплаты'),
        ),
    ]
