# Generated by Django 5.2.4 on 2025-09-02 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0056_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='possible_restaurants',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='foodcartapp.restaurant', verbose_name='Рестораны, способные выполнить заказ'),
        ),
    ]
