# Generated by Django 5.2.4 on 2025-09-07 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0058_alter_order_called_at_alter_order_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, max_length=450, verbose_name='Коментарий'),
        ),
    ]
