# Generated by Django 5.2.4 on 2025-09-03 12:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Локация', 'verbose_name_plural': 'Локации'},
        ),
        migrations.AlterField(
            model_name='location',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, default=datetime.datetime(2025, 9, 3, 12, 35, 8, 749120, tzinfo=datetime.timezone.utc), null=True, verbose_name='Создано'),
        ),
    ]
