# Generated by Django 5.2.4 on 2025-09-03 13:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_alter_location_options_alter_location_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='location',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, default=datetime.datetime(2025, 9, 3, 13, 6, 48, 78439, tzinfo=datetime.timezone.utc), null=True, verbose_name='Создано'),
        ),
    ]
