# Generated by Django 5.2.4 on 2025-09-07 10:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_alter_location_created_at_alter_location_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, default=datetime.datetime(2025, 9, 7, 10, 51, 28, 629106, tzinfo=datetime.timezone.utc), null=True, verbose_name='Создано'),
        ),
    ]
