# Generated by Django 5.2.4 on 2025-09-07 11:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_alter_location_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, default=datetime.datetime(2025, 9, 7, 11, 6, 8, 23367, tzinfo=datetime.timezone.utc), null=True, verbose_name='Создано'),
        ),
    ]
