# Generated by Django 5.2.4 on 2025-09-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0008_alter_location_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='created_at',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='Создано'),
        ),
    ]
